# Default values for goci-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

stage: staging
name: my-app

replicaCount: 3

image:
  name: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

health:
  path: /health

readiness:
  path: /health

podAnnotations: {}

nodeSelector: {}

autoscaling: 
  enabled: false
  # minReplicas: 3
  # maxReplicas: 6
  # targetAverageUtilization: 60
  # targetRequestsPerSecond: 10k

podDisruptionBudget:
  enabled: true
  minUnavailable: 1

metrics:
  enabled: false
  port: http
  interval: 60s
  serviceMonitor:
    enabled: false
