{{- if and .Values.rbac.create and (len .Values.rbac.additionalRules gt 0) and not .Values.rbac.appUser not .Values.rbac.appUser.create and not .Values.rbac.superUser not .Values.rbac.superUser.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.roleName | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: Service
    {{ include "goci-service.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.additionalRules }}
{{ toYaml . }}
{{- end }}
{{- end }}
