{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.appUser.create }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ .Values.rbac.roleName | default .Release.Name }}
{{- if .Values.rbac.appUser.create }}
  namespace: user-1-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.roleName | default .Release.Name }}
{{- else }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.roleName | default .Release.Name }}
{{- end }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount | default .Release.Name }}
{{- end }}
