apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goci-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: Service
{{ include "goci-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      namespace: {{ .Release.Namespace }}
      app.kubernetes.io/name: {{ include "goci-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        type: Service
{{ include "goci-service.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      annotations:
    spec:
      securityContext:
        runAsUser: {{ .Values.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.runAsGroup | default 1000 }}
      terminationGracePeriodSeconds: 300
      serviceAccountName: {{ .Release.Namespace }}-apps
      containers:
        - name: app
          {{- if .Values.image.repository -}}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port | default 8080 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http
              initialDelaySeconds: 15
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              initialDelaySeconds: 15
              port: http
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "goci-service.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
