apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goci-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: Service
{{ include "goci-service.labels" . | indent 4 }}
data:
{{ toYaml .Values.secrets | nindent 2 }}
