apiVersion: v1
kind: Service
metadata:
  name: {{ include "goci-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: Service
{{ include "goci-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "goci-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
